### ISSUE TITLE
stream-album throws PlayerError

### ISSUE THREAD

**Issue by JensDA** [iamdb/hifi.rs#119]
Hi, I just found this repo. Thank you for your efforts to make Qobuz working on Linux.
Unfortunately, I can't get it to work:

    ./hifi-rs stream-album huquowkjgyhpb
    Error: PlayerError { error: TrackURL }

Username/Password are correct, since `hifi-rs my-playlists -o tsv` is working.
However, `hifi-rs my-playlists` is not working:

    ./hifi-rs my-playlists
    thread 'main' panicked at 'database failure: RowNotFound', /home/runner/work/hifi.rs/hifi.rs/hifirs/src/sql/db.rs:198:18

Also, could you please provide an example of a URI for the play command?

**Comment by iamdb** [comment]
@JensDA, I made some fixes that I think should solve the issues you were having. Thank you again for reporting it.

**Comment by JensDA** [comment]
Thanks, it works.
However, after it working twice, I can not start it again:

    target/debug/hifi-rs my-playlists
    Error: PlayerError { error: Resume }

    target/debug/hifi-rs reset
    thread 'main' panicked at 'failed to clear state: Database(SqliteError { code: 1, message: "no such table: state" })', /home/jens/repositories/hifi.rs/hifirs/src/sql/db.rs:59:18

The only thing I changed between tries is adding and switching to a different audio interface.

**Comment by iamdb** [comment]
Was that with the same database as before? If so, would you mind trying a fresh one?

That error definitely shouldn't be happening so I want to make sure nothing weird happened with the db between builds.

If that error is with a fresh database, would you mind sending me what you played last?

**Comment by JensDA** [comment]
It does happen with a fresh database. I played `https://open.qobuz.com/track/49067300` from a playlist this time, but it was something different before.

**Comment by JensDA** [comment]
If I start with `hifi-rs play {uri}` it works, but `my-playlists` still does not.

**Comment by iamdb** [comment]
@JensDA, one thing to note that isn't obvious at all is that tracks won't work with the uri feature. Can you try the code on the fix-119-v2 branch with an album URI and see if it works as expected? I put in some checks/guards so it gives more helpful error messages, too.

If that works, then it mainly means I need to do work on cleaning up the track parts which shouldn't be a problem.

**Comment by JensDA** [comment]
I've narrowed the failing path a bit. This is with the main branch still.
The issue occurs when doing this:

1. `hifi-rs my-playlists`
2. Select a playlist and choose `play`, let it play for a few seconds, then `Ctrl+C`.
3. try `hifi-rs my-playlists` again -> `Error: PlayerError { error: Resume }`
4. If I now execute for example `./hifi-rs play --uri "https://play.qobuz.com/album/xtciz3u7m5i8a"` and close again.
5. try `hifi-rs my-playlists` again -> works as intended. Until trying once more, when the issue occurs again.

**Comment by iamdb** [comment]
@JensDA I think I fixed the remaining issues and playback of tracks using the uri should also work now.

If you can give this branch a try, it would be appreciated.

https://github.com/iamdb/hifi.rs/tree/fix-119-v2

**Comment by JensDA** [comment]
Works for me, thank you!

**Comment by iamdb** [comment]
Awesome! Definitely let me know if you run into other issues.
